version: '3.7'

services:
  backend-restful-api:
    container_name: backend-restful-api
    image: backend-restful-api:0.0.3
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: dheva
      DATABASE_PASSWORD: tugasakhir
      DATABASE_URL: jdbc:postgresql://restful-api-postgres:5432/restful-api

  restful-api-postgres:
    container_name: "restful-api-postgres"
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: tugasakhir
      POSTGRES_USER: dheva
      POSTGRES_DB: restful-api